### PR TITLE
Make it build with ghc-9.8 (update deps only)

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
@sw17ch Ping ?

**Review by jeremyjh — APPROVED** [review]
Thank you. I was able to test successfully. I haven't Haskelled in years but I shall endeavor to review the other PRs and then cut a package tomorrow if I can figure it out.

**Comment by erikd** [comment]
I am a Hackage Trustee so I can edit the Hackage metadata if you like.

**Comment by jeremyjh** [comment]
Oh I forgot that was a thing, I've just done it that way thanks.

**Pull request merged**
